---
# Install Adminer.
- name: Ensure Adminer directory exists.
  file:
    path: "{{ adminer_install_dir }}"
    state: directory
    recurse: yes

- name: Download Adminer to configured directory.
  get_url:
    url: http://www.adminer.org/latest.php
    dest: "{{ adminer_install_dir }}/{{ adminer_install_filename }}"
    mode: 0644

- name: Symlink Adminer into configured directories.
  file:
    src: "{{ adminer_install_dir }}/{{ adminer_install_filename }}"
    dest: "{{ item }}/{{ adminer_install_filename }}"
    state: link
  with_items: adminer_symlink_dirs