---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: Add ppa Repository
  sudo: yes
  apt_repository: repo=ppa:ondrej/{{ mysql.ppa }}

- name: mysql | Install MySQL Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }} check_implicit_admin=yes password={{ mysql.root_password }} login_user=root login_password={{ mysql.root_password }}
  with_items:
    - "{{ current_hostname.stdout | lower }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: mysql | Create databases
  mysql_db: name={{ item.database }} state=present login_user=root login_password={{ mysql.root_password }} encoding=utf8
  with_items: mysql.databases
  when: mysql.databases

- name: mysql | Create users
  mysql_user: name={{ item.user }} password={{ item.password }} priv={{ item.database }}.*:ALL state=present login_user=root login_password={{ mysql.root_password }}
  with_items: mysql.users
  when: mysql.users

- name: mysql | Import dump
  mysql_db: name={{ item.database }} state=import login_user=root login_password={{ mysql.root_password }} target={{ item.dump }}
  with_items: mysql.dumps
  when: mysql.dumps

- name: mysql | Ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent login_user=root login_password={{ mysql.root_password }}
  with_items:
    - localhost
    - "{{ current_hostname.stdout | lower }}"
