---
server:
    install: '1'
    packages: [htop, git, mc, gcc, autoconf, re2c, make, automake, libpcre3, libpcre3-dev, libssl1.0.0, libssl-dev, libcurl3, libcurl4-openssl-dev]
    timezone: Europe/Kiev
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm:
        hostname: blog-mvc.lan
nginx_sendfile: "off"
nginx_vhosts:
  - listen: "80"
    server_name: "192.168.66.66 blog-mvc.lan"
    root: "/var/www/html"
    index: "index.php index.html index.htm"
    extra_parameters: |
      location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
      }

mysql_root_password: "temp123"
mysql_user_home: "/home/vagrant"
mysql_root_password_update: "yes"
mysql_packages:
  - mariadb-client
  - mariadb-server

mysql_databases:
    - { name: blog }
mysql_users:
    - { name: blog, password: blog, priv: 'blog%.*:ALL' }
mysql_dumps:
    - { database: blog, dump: /var/www/blog-mvc/dump.sql }

php_packages:
  - php7.0
  - php7.0-fpm
  - php7.0-curl
  - php7.0-cli
  - php7.0-intl
  - php7.0-json
  - php7.0-dev
  - php7.0-mysql
  - php7.0-opcache
  - php-memcached
  - php7.0-mbstring
  - php7.0-mcrypt
  - php7.0-bcmath

php_executable: "php"
php_fpm_daemon: "php7.0-fpm"
php_webserver_daemon: "nginx"
php_enable_php_fpm: true

php_date_timezone: "Europe/Kiev"
php_error_reporting: "E_ALL"
php_memory_limit: "512M"
php_display_errors: "On"
php_display_startup_errors: "On"

php_enable_apc: false

php_fpm_listen: "/var/run/php/php7.0-fpm.sock"

php_conf_paths:
  - /etc/php/7.0/fpm
  - /etc/php/7.0/cli
php_extension_conf_paths:
  - /etc/php/7.0/fpm/conf.d
  - /etc/php/7.0/cli/conf.d
php_fpm_conf_path: "/etc/php/7.0/fpm"
php_fpm_pool_conf_path: "/etc/php/7.0/fpm/pool.d/www.conf"

php_xdebug_default_enable: "true"
php_xdebug_remote_enable: "true"
php_xdebug_coverage_enable: "true"
php_xdebug_remote_connect_back: "true"
php_xdebug_remote_cookie_expire_time: 86400

phalcon:
    version: '2.1.x'

adminer_symlink_dirs: ['/var/www/html']

nodejs_version: 'nodejs-v5x'
nodejs_npm_packages:
    - 'grunt'
    - 'grunt-cli'
    - 'gulp'
    - 'bower'
app:
    nginx:
        errors: []
    environments: [blog-mvc]
swap_size: '2048'