---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - swap
    - server
    - vagrant_local
    - geerlingguy.nginx
    - geerlingguy.mysql
#    - mysql
    - tankist.php-fpm
    - phalcon
    - tankist.php-xdebug
    - T2L.composer
    - Oefenweb.nodejs
    - geerlingguy.adminer
    - app
