---
- hosts: all
  become: true
  vars_files:
    - vars/all.yml

  pre_tasks:
    - name: Add repository for PHP 7.
      apt_repository: repo='ppa:ondrej/php'
      when: ansible_os_family == 'Debian'

  roles:
    - swap
    - server
    - vagrant_local
    - geerlingguy.nginx
    - geerlingguy.mysql
#    - mysql
    - geerlingguy.php
    - phalcon
    - geerlingguy.php-xdebug
    - T2L.composer
    - Oefenweb.nodejs
    - geerlingguy.adminer
    - app
