---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - swap
    - nginx
    - mysql
    - php
    - phalcon
    - xdebug
    - composer
    - adminer
    - app
