---
- name: Install xDebug
  sudo: yes
  apt: pkg=php5-xdebug state=latest

- name: Copy xdebug INI into php.d folder.
  template:
    src: xdebug.ini.j2
    dest: "/etc/php5/mods-available/xdebug.ini"
    owner: root
    group: root
    mode: 0644
  notify: restart php5-fpm
  register: xdebug_ini
  
- name: Xdebug module enabled
  file:
    path=/etc/php5/{{ item.path }}/conf.d/20-xdebug.ini
    src=/etc/php5/mods-available/xdebug.ini
    state=link
    owner=root group=root
  with_items:
    - { path: 'fpm' }
    - { path: 'cli' }
  when: xdebug_ini|changed
  sudo: yes
  notify: restart php5-fpm